######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 27 16:10:59 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += seqlist.h
SOURCES += main.cpp
