######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 27 17:04:29 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += binaryTree.h
SOURCES += main.cpp
